[user]
name = "Andrey Albershteyn"
email = "aalbersh@kernel.org"

[aliases]
l = ["log", "-r", "ancestors(reachable(@, mutable()), 2)", "--limit", "25"]

[ui]
default-command = "l"
pager = "bat --plain --tabs 8"
paginate = "auto"

[templates]
commit_trailers = '''
"Signed-off-by: " ++ committer ++ "\n"
'''

[colors]
# Highlight hunks with background
"diff removed token" = { bg = "#221111", underline = false }
"diff added token" = { bg = "#002200", underline = false }
