# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];

  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/dcd342c5-7ade-4f5f-80f9-632606539158";
    fsType = "xfs";
  };

  swapDevices = [{device = "/dev/disk/by-uuid/0fa090c1-e8a7-45fb-9be3-83598593a4cb";}];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/813B-756B";
    fsType = "vfat";
  };

  fileSystems."/media" = {
    device = "/dev/disk/by-uuid/44712d0a-dab1-4c5f-9bc8-5f29df1c1e6e";
    label = "storage";
    fsType = "xfs";
  };

  # Enables DHCP on each ethernet and wireless interface. In case of
  # scripted networking (the default) this is the recommended approach.
  # When using systemd-networkd it's still possible to use this option,
  # but it's recommended to use it in conjunction with explicit
  # per-interface declarations with
  # `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
