[user]
name = "Andrey Albershteyn"
email = "aalbersh@kernel.org"

[fsmonitor]
backend = "watchman"
watchman.register-snapshot-trigger = true

[aliases]
l = ["log", "-r", "ancestors(reachable(@, mutable()), 2)", "--limit", "25"]
la = ["log", "-r", "all()"]
lm = ["log", "-T", "builtin_log_detailed"]
lp = ["log", "--patch"]
lg = ["log", "--patch", "-T", "builtin_log_detailed"]
cm = ["commit"]
fp = ["show", "--git", "--template", "git_format_patch_email_headers"]
mine = ["bookmark", "list", "-r", "mine()"]

[ui]
default-command = "l"
pager = "bat --plain --tabs 8"
paginate = "auto"
merge-editor = "mergiraf"

[colors]
# Highlight hunks with background
"diff removed token" = { bg = "#221111", underline = false }
"diff added token" = { bg = "#002200", underline = false }

[templates]
draft_commit_description = '''
  concat(
    coalesce(description, default_commit_description, "\n"),
    surround(
      "\nJJ: This commit contains the following changes:\n", "",
      indent("JJ:     ", diff.stat(72)),
    ),
    "\nJJ: ignore-rest\n",
    diff.git(),
  )
'''
